In [1]:
import numpy as np

In [2]:
dataset = np.array([['Lamm bog rå', '920', '133.6', '558.8', '0.0', '5.9', '20.13'],
   ['Lamm kotlett rå', '921', '232.2', '971.6', '0.0', '17.3', '19.0'],
   ['Lamm lägg rå', '922', '136.7', '571.9', '0.0', '4.2', '24.5'],
   ['Lamm rygg lamm hals rå', '923', '176.7', '739.5', '0.0', '11.9', '17.6'],
   ['Kalv fransyska rå', '937', '108.3', '453.0', '0.0', '3.1', '19.9'],
   ['Kalv innanlår rå', '938', '107.4', '449.5', '0.0', '2.5', '21.0'],
   ['Kalv kotlett rå', '939', '122.2', '511.3', '0.0', '4.4', '20.5'],
   ['Kalv lägg rå', '940', '98.1', '410.3', '0.0', '1.9', '20.0']])

In [3]:
dataset

array([['Lamm bog rå', '920', '133.6', '558.8', '0.0', '5.9', '20.13'],
       ['Lamm kotlett rå', '921', '232.2', '971.6', '0.0', '17.3',
        '19.0'],
       ['Lamm lägg rå', '922', '136.7', '571.9', '0.0', '4.2', '24.5'],
       ['Lamm rygg lamm hals rå', '923', '176.7', '739.5', '0.0', '11.9',
        '17.6'],
       ['Kalv fransyska rå', '937', '108.3', '453.0', '0.0', '3.1',
        '19.9'],
       ['Kalv innanlår rå', '938', '107.4', '449.5', '0.0', '2.5',
        '21.0'],
       ['Kalv kotlett rå', '939', '122.2', '511.3', '0.0', '4.4', '20.5'],
       ['Kalv lägg rå', '940', '98.1', '410.3', '0.0', '1.9', '20.0']],
      dtype='<U22')

Kolumnerna:

```
[0 'Livsmedelsnamn' 'TEXT' 0 None 0]
[1 'Livsmedelsnummer' 'TEXT' 0 None 0]
[2 'Energi_kcal' 'REAL' 0 None 0]
[3 'Energi_kJ' 'REAL' 0 None 0]
[4 'Kolhydrater_g' 'REAL' 0 None 0]
[5 'Fett_g' 'REAL' 0 None 0]
[6 'Protein_g' 'REAL' 0 None 0]
```

In [4]:
#Adressera en rad:
print(dataset[3])

['Lamm rygg lamm hals rå' '923' '176.7' '739.5' '0.0' '11.9' '17.6']


In [5]:
#Adressera en cell:
print(dataset[3,1]) #Man kan också skriva dataset[3,1]

923


In [6]:
#För att adressera en kolumn transponerar man matrisen, med .T
print (dataset.T)

[['Lamm bog rå' 'Lamm kotlett rå' 'Lamm lägg rå' 'Lamm rygg lamm hals rå'
  'Kalv fransyska rå' 'Kalv innanlår rå' 'Kalv kotlett rå' 'Kalv lägg rå']
 ['920' '921' '922' '923' '937' '938' '939' '940']
 ['133.6' '232.2' '136.7' '176.7' '108.3' '107.4' '122.2' '98.1']
 ['558.8' '971.6' '571.9' '739.5' '453.0' '449.5' '511.3' '410.3']
 ['0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0']
 ['5.9' '17.3' '4.2' '11.9' '3.1' '2.5' '4.4' '1.9']
 ['20.13' '19.0' '24.5' '17.6' '19.9' '21.0' '20.5' '20.0']]


In [26]:
#Detta blir alltså alla värden för energi i kcal.
print (dataset.T[2])
#Men det är mycket snyggare att använda slices. Se nästa stycke.

['133.6' '232.2' '136.7' '176.7' '108.3' '107.4' '122.2' '98.1']


## Slices

Allt i den här anteckningsboken bygger ju på att man lär sig funktioner när man behöver dem, så hoppa över den här om den inte är aktuell.

Vitsen med funktionen är att skära ut ett antal sammanhängande rader eller kolumner ur sin datamängd. Det kan vara för att ta bort en header, eller för att ta bort rader eller kolumner på slutet för att göra data mer överskådliga.

Syntaxen är lite svår att läsa innan man har vant sig. Index för matrisen är i rader och kolumner, och de avgränsas av ett ",".

Ett ":" markerar ett intervall som är öppet om man inte skriver något slut. Så "2:" betyder börja på element 2 och ta med alla element därefter.

Vill man ta bort första raden blir det 

```
dataset[1:,:]
```

Vill man ta bort första två kolumnerna blir det 

```
dataset[:,2:]
```

Slices funkar även för vanliga listor. Inte bara i numpy

In [8]:
print (dataset[:,1:])

[['920' '133.6' '558.8' '0.0' '5.9' '20.13']
 ['921' '232.2' '971.6' '0.0' '17.3' '19.0']
 ['922' '136.7' '571.9' '0.0' '4.2' '24.5']
 ['923' '176.7' '739.5' '0.0' '11.9' '17.6']
 ['937' '108.3' '453.0' '0.0' '3.1' '19.9']
 ['938' '107.4' '449.5' '0.0' '2.5' '21.0']
 ['939' '122.2' '511.3' '0.0' '4.4' '20.5']
 ['940' '98.1' '410.3' '0.0' '1.9' '20.0']]


## Välja kolumner
I numpy kan man på ett enkelt sätt filtrera bort kolumner. Om man vill ha bara livsmedelsnamnet och proteinhalten så ligger de i kolumn 0 och 6. Jag gör en array av dem och har som index till dataset.

In [9]:
columns = [0,1]

In [25]:
print(dataset[:,columns]) 

[['Lamm bog rå' '920']
 ['Lamm kotlett rå' '921']
 ['Lamm lägg rå' '922']
 ['Lamm rygg lamm hals rå' '923']
 ['Kalv fransyska rå' '937']
 ['Kalv innanlår rå' '938']
 ['Kalv kotlett rå' '939']
 ['Kalv lägg rå' '940']]


## Lägga till kolumner

Säg att jag kör en sökning i en extern databas för att kolla vilka av dessa som är bra att steka. Jag får ett värde tillbaka för varje livsmedel:

In [22]:
bra_att_steka = np.array([[False, True, False, True, True, False, True, False]])
bra_att_steka.shape

(1, 8)

Nu vill jag lägga till de här värdena till mitt dataset, i en ny kolumn. Då använder jag numpys concatenate.

Obs när jag skapar bra_att_steka så behövs extra hakparenteser för att concatenate ska vilja sätta ihop arrayerna. De måste ha samma antal dimensioner.

In [12]:
new = np.concatenate((dataset,bra_att_steka.T),axis=1) #https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.concatenate.html#numpy.concatenate
#Om jag anger axis=0 försöker den lägga till värdena som en rad i stället för som en kolumn
print(new)

[['Lamm bog rå' '920' '133.6' '558.8' '0.0' '5.9' '20.13' 'False']
 ['Lamm kotlett rå' '921' '232.2' '971.6' '0.0' '17.3' '19.0' 'True']
 ['Lamm lägg rå' '922' '136.7' '571.9' '0.0' '4.2' '24.5' 'False']
 ['Lamm rygg lamm hals rå' '923' '176.7' '739.5' '0.0' '11.9' '17.6'
  'True']
 ['Kalv fransyska rå' '937' '108.3' '453.0' '0.0' '3.1' '19.9' 'True']
 ['Kalv innanlår rå' '938' '107.4' '449.5' '0.0' '2.5' '21.0' 'False']
 ['Kalv kotlett rå' '939' '122.2' '511.3' '0.0' '4.4' '20.5' 'True']
 ['Kalv lägg rå' '940' '98.1' '410.3' '0.0' '1.9' '20.0' 'False']]


## Hitta celler med visst villkor

Man kan skicka in ett villkor på hela sin array, och i retur får man en ny array av samma form. Syntaxen är lömskt enkel:

```
new == 'True'
```

In [13]:
print(new == '0')

[[False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]]


Om man vill ha ut vilka celler som uppfyller villkoret finns det ett kommando np.where().

In [14]:
steka = np.array(np.where(new == 'True'))

In [15]:
steka

array([[1, 3, 4, 6],
       [7, 7, 7, 7]])

steka[0] blir ju då en lista med raderna som är bra att steka.

In [16]:
print(steka[0])

[1 3 4 6]


In [17]:
dataset[steka[0]]

array([['Lamm kotlett rå', '921', '232.2', '971.6', '0.0', '17.3',
        '19.0'],
       ['Lamm rygg lamm hals rå', '923', '176.7', '739.5', '0.0', '11.9',
        '17.6'],
       ['Kalv fransyska rå', '937', '108.3', '453.0', '0.0', '3.1',
        '19.9'],
       ['Kalv kotlett rå', '939', '122.2', '511.3', '0.0', '4.4', '20.5']],
      dtype='<U22')

Det finns en del inbyggda strängfunktioner i numpy också, men de är lite mer komplicerade. Man kan exempelvis fråga efter vilka celler som börjar med en viss sträng, så här:

In [18]:
np.char.startswith(new,'Lamm') #https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.core.defchararray.startswith.html 

array([[ True, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

## Reshape till rätt antal dimensioner
Man behöver ofta göra om endimensionella listor till tvådimensionella arrayer med "bredden" 1. Frågar man om shape för en vanlig lista blir den (5,). En tvådimensionell blir (5,1). Index -1 betyder sista cellen. Därför kan man också göra reshape till -1 i stället för att behöva göra det till len(lista) för att få fram längden på listan.

In [20]:
lista = [1,2,3,4,5]
lista = np.array(lista)
print(lista, len(lista), lista.shape, '\n')
#lista = lista.reshape(len(lista),1)
lista = lista.reshape(-1,1)
print(lista, len(lista), lista.shape)
lista[-1]

[1 2 3 4 5] 5 (5,) 

[[1]
 [2]
 [3]
 [4]
 [5]] 5 (5, 1)


array([5])