In [2]:
import sqlite3
import numpy as np
from sklearn.cluster import KMeans
import plotly
import plotly.graph_objs as go
import plotly.plotly as py

ImportError: No module named plotly

In [40]:
conn = sqlite3.connect('livs.db')  # create db and establish connection

In [41]:
conn.row_factory = sqlite3.Row

In [42]:
curs = conn.cursor()

In [43]:
result = []

In [44]:
for row in curs.execute('select "Kolhydrater_g", "Fett_g", "Protein_g" from livs'):
        result.append(row)

In [45]:
conn.close()

In [51]:
dataSet = np.array(result)
debug = True

In [52]:
print dataSet

[[   0.     71.      7.  ]
 [   0.     85.      2.8 ]
 [   0.    100.      0.  ]
 ..., 
 [  72.6     3.55    5.63]
 [  57.5     4.8     8.44]
 [  19.2    48.67   18.  ]]


In [53]:
def cluster(dataSet):

    kmeans = KMeans(n_clusters=numClusters)
    kmeans.fit(dataSet)

    centroids = kmeans.cluster_centers_
    labels = kmeans.labels_

    if debug:
        print (centroids)
        print (labels)

    return labels

In [59]:
numClusters = 2
labels = cluster(dataSet)

[[  7.85044092  10.44917108   8.61170488]
 [ 59.78520833   9.35570312   7.35177083]]
[0 0 0 ..., 1 1 0]


In [60]:
# transpose to work with Plotly-format (don't remember if it is sklear.cluster or plotly that is counterintuitive)
dataToChart = dataSet.transpose()

In [61]:
print dataToChart

[[   0.      0.      0.   ...,   72.6    57.5    19.2 ]
 [  71.     85.    100.   ...,    3.55    4.8    48.67]
 [   7.      2.8     0.   ...,    5.63    8.44   18.  ]]


In [63]:
# create multi dimensional array of data by label
segmentedData = [[[] for _ in xrange(3)] for _ in xrange(numClusters)]

In [64]:
for num, label in enumerate(labels):
        print (str(num) + ' ' + str(label))
        segmentedData[label][0].append(dataToChart[0][num])
        segmentedData[label][1].append(dataToChart[1][num])
        segmentedData[label][2].append(dataToChart[2][num])

0 0
1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
10 0
11 0
12 0
13 0
14 0
15 0
16 0
17 0
18 0
19 0
20 0
21 0
22 0
23 0
24 0
25 0
26 0
27 0
28 0
29 0
30 0
31 0
32 0
33 0
34 0
35 0
36 0
37 0
38 0
39 0
40 0
41 0
42 0
43 0
44 0
45 0
46 0
47 0
48 0
49 0
50 0
51 0
52 0
53 0
54 0
55 1
56 1
57 1
58 1
59 1
60 0
61 0
62 0
63 0
64 0
65 0
66 0
67 0
68 0
69 0
70 0
71 0
72 0
73 0
74 0
75 0
76 0
77 0
78 0
79 0
80 0
81 0
82 0
83 0
84 0
85 0
86 0
87 0
88 0
89 0
90 0
91 0
92 0
93 0
94 0
95 0
96 0
97 0
98 0
99 0
100 0
101 0
102 0
103 0
104 0
105 1
106 1
107 0
108 0
109 0
110 0
111 0
112 0
113 0
114 0
115 0
116 0
117 0
118 0
119 0
120 0
121 0
122 0
123 0
124 0
125 0
126 0
127 0
128 0
129 0
130 0
131 0
132 0
133 0
134 0
135 1
136 1
137 1
138 1
139 1
140 1
141 1
142 1
143 1
144 1
145 1
146 1
147 1
148 1
149 1
150 1
151 1
152 1
153 1
154 1
155 1
156 1
157 1
158 1
159 1
160 1
161 1
162 1
163 1
164 1
165 1
166 1
167 1
168 1
169 1
170 1
171 1
172 1
173 1
174 1
175 1
176 1
177 1
178 1
179 1
180 1
181 1
182 1
183 1
184 1


In [65]:
if debug:
        print(segmentedData)

[[[0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.29999999999999999, 0.29999999999999999, 0.0, 0.0, 0.40000000000000002, 0.5, 3.0, 2.5, 6.2000000000000002, 0.40999999999999998, 3.9199999999999999, 12.33, 13.1, 1.0700000000000001, 3.3199999999999998, 8.0, 5.5, 0.5, 0.47999999999999998, 0.47999999999999998, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 9.6999999999999993, 9.5, 24.0, 19.699999999999999, 8.0, 15.0, 20.800000000000001, 13.1, 1.5, 10.9, 2.8999999999999999, 8.5, 9.1699999999999999, 10.050000000000001, 2.5, 1.1799999999999999, 0.45000000000000001, 6.3899999999999997, 2.2000000000000002, 6.7000000000000002, 6.5999999999999996, 2.1000000000000001, 9.0999999999999996, 0.90000000000000002, 2.8999999999999999, 3.1000000000000001, 3.6000000000000001, 2.8999999999999999, 1.5, 0.80000000000000004, 1.3999999999999999, 1.2, 0.0, 1.5, 0.5, 0.29999999999999999, 0.10000000000000001, 1.5, 2.0, 2.0, 1.5, 1.5, 1.5, 2.1000000000000001, 0.90000000000000002, 0.80000000000000004, 1.5, 1.3999999999999999, 1.3999999999

In [68]:
# create traces for plotly
traces = []
baseColor = 100
i = 0
while i < numClusters:
    trace = go.Scatter3d(
        x=segmentedData[i][0],
        y=segmentedData[i][1],
        z=segmentedData[i][2],
        mode='markers',
        marker=dict(
            size=12,
            line=dict(
                color='rgba(baseColor+(i*2), baseColor+(i*2), baseColor+(i*2), 0.14)',
                width=0.5
            ),
            opacity=0.8
        ),
        # @todo: fix names list for plotly
        #text=names
    )
    traces.append(trace)
    i+=1


NameError: name 'go' is not defined