## Att leka med kluster av mat

Det finns över tvåtusen livsmedel i Livsmedelsdatabasen, och de har värden för över 50 näringsvärden.

Att sortera dem i Excel funkar ett tag, men det blir svårt att få en samlad bedömning eller gruppering av stora mängder livsmedel.

Det finns också en metadataklassificering som Livsmedelsverket kallar "huvudgrupp". Det är en klassificering som bara har en nivå. Inget över, inget under. En flat nivå.

In [112]:
import sqlite3
import numpy as np
from sklearn.cluster import KMeans

In [113]:
debug = True

Börja med att läsa in allt från databasen. Det tar inte så mycket minne, men är svårt att få överblick över.

Allt ligger i variabeln dataset som är en numpy-array. Man kan skriva ut den eller delar av den när som helst om man vill se vad som ligger på en viss rad eller en viss kolumn. Kolumn 0 är livsmedelsnamnet, 1 är livsmedelsnumret.

In [114]:
conn = sqlite3.connect('livs.db')
conn.row_factory = sqlite3.Row
curs = conn.cursor()

result = []
for row in curs.execute('select * from livs'):
    result.append(row)

conn.close()

dataset = np.array(result)
if debug:
    print (dataset[:5,:5])

[['Talg nöt' '1' 656.3 2746.0 0.0]
 ['Späck gris' '2' 763.0 3192.6 0.0]
 ['Ister gris' '3' 884.3 3700.0 0.0]
 ['Kokosfett' '4' 884.3 3700.0 0.0]
 ['Matfettsblandning havssaltat fett 80% berikad typ Bregott' '5' 711.5
  2977.0 0.5]]


Livsmedelsverkets gruppering har jag lagt i kolumn 60. Numpy-funktionen np.unique() returnerar både alla unika värden och (om man vill) hur många som är i varje kategori.

In [115]:
unique, counts = np.unique(dataset.T[60], return_counts=True) #https://stackoverflow.com/questions/28663856/how-to-count-the-occurrence-of-certain-item-in-an-ndarray-in-python
huvudgrupp_storlek = np.array(list(zip(unique, counts)))

Skriver man ut huvudgrupp_storlek blir det typ 118 kategorier i bokstavsordning. Här är de n första.

In [116]:
n = 20
print (huvudgrupp_storlek[:])

[['' '7']
 ['Algprodukter' '1']
 ['Baljväxter (bönor, linser och ärter)' '51']
 ['Blodmat' '2']
 ['Blodprodukter o rätter' '8']
 ['Buljong' '18']
 ['Bullar kakor tårtor mm' '86']
 ['Bär färska frysta' '24']
 ['Chips popcorn o dyl' '11']
 ['Choklad' '7']
 ['Cider alkoläsk drink' '3']
 ['Deg och gräddade skal och bottnar' '3']
 ['Dessertost' '8']
 ['Dryck' '1']
 ['Efterrätter' '31']
 ['Fisk färsk fryst kokt' '68']
 ['Fisk o skaldjursprodukter o rätter' '69']
 ['Fisk rökt' '13']
 ['Fisk stekt ej panerad' '7']
 ['Flingor - frukostflingor' '28']
 ['Flytande matfettsblandning' '7']
 ['Frukt färsk fryst' '42']
 ['Frukt o bär' '2']
 ['Frukt o bär konserverade' '17']
 ['Frukt o bär torkade' '14']
 ['Frukt o nötblandningar bars' '2']
 ['Fruktjuice mm' '22']
 ['Färskost o kvarg' '15']
 ['Fågel' '39']
 ['Fågelprodukter o rätter' '5']
 ['Gelatin agar agar' '2']
 ['Glass' '25']
 ['Godis ej choklad' '11']
 ['Godis som innehåller choklad' '15']
 ['Grädde creme fraiche' '23']
 ['Grönsaker' '94']
 ['Grö

Jag förstår inte riktigt varför det är så svårt att sortera den arrayen. Det är ju en sak att allting är strängar, eftersom en numpy-array bara kan ha en enda datatyp, men det borde finnas ett enkelt sätt att sortera efter kolumn två som integer...

Som det blir nu behöver man skapa ett index genom att använda np.argsort, ta de 20 första med [-20:] och sen vända på ordningen med [::-1], som helt enkelt är en slice till, där -1 är step-argumentet. https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html 

In [117]:
antal = 20
index = np.argsort(huvudgrupp_storlek.T[1].astype(int))[-antal:][::-1] #https://stackoverflow.com/questions/6910641/how-to-get-indices-of-n-maximum-values-in-a-numpy-array
print(huvudgrupp_storlek[index])

[['Kött färskt fryst tillagat' '127']
 ['Grönsaker' '94']
 ['Bullar kakor tårtor mm' '86']
 ['Köttprodukter kötträtter' '80']
 ['Sås dressing majonnäs' '79']
 ['Fisk o skaldjursprodukter o rätter' '69']
 ['Fisk färsk fryst kokt' '68']
 ['Korv' '60']
 ['Grönsaks- rotfrukts- baljväxträtter och produkter' '55']
 ['Baljväxter (bönor, linser och ärter)' '51']
 ['Soppa mat' '47']
 ['Pizza paj pirog färdig smörgås' '46']
 ['Frukt färsk fryst' '42']
 ['Mjukt bröd' '42']
 ['Hård matfettsblandning' '39']
 ['Fågel' '39']
 ['Potatisprodukter o rätter' '33']
 ['Inälvor och organ' '33']
 ['Potatis' '31']
 ['Efterrätter' '31']]


Medan de största grupperna är ganska rättframma är de minsta desto knepigare. Vad ska man göra med en klassificering som innehåller en huvudgrupp "Risrätter" med endast ett livsmedel, och det är paella och inte exempelvis risgrynsgröt?

In [118]:
index = np.argsort(huvudgrupp_storlek.T[1].astype(int))[:20] #https://stackoverflow.com/questions/6910641/how-to-get-indices-of-n-maximum-values-in-a-numpy-array
print(huvudgrupp_storlek[index])

[['Sötningsmedel' '1']
 ['Algprodukter' '1']
 ['Kryddor' '1']
 ['Övrigt animaliskt *kött*, grodlår, sniglar, säl - färskt, fryst, tillagat'
  '1']
 ['Sockerfritt godis' '1']
 ['Risrätter' '1']
 ['Dryck' '1']
 ['Tacoskal' '1']
 ['Riskakor' '2']
 ['Frukt o nötblandningar bars' '2']
 ['Frukt o bär' '2']
 ['Sportdrycker energidrycker' '2']
 ['Gelatin agar agar' '2']
 ['Övrigt' '2']
 ['Blodmat' '2']
 ['Tuggummi' '2']
 ['Kakaoprodukter' '2']
 ['Cider alkoläsk drink' '3']
 ['Osträtter' '3']
 ['Smör' '3']]


Det går ju även att få fram vilka livsmedel som finns i de där grupperna.

In [119]:
for row in huvudgrupp_storlek[index]:
    q = np.where(dataset.T[60]==row[0])
    print(row[0],"\n",dataset[q,0]) #Det går ju att skriva ut vilka värden som helst för varje livsmedel, som med dataset[q,:]

Sötningsmedel 
 [['Sorbitol m sackarin']]
Algprodukter 
 [['Kelp torkad']]
Kryddor 
 [['Kryddblandning taco']]
Övrigt animaliskt *kött*, grodlår, sniglar, säl - färskt, fryst, tillagat 
 [['Grodlår råa frysta']]
Sockerfritt godis 
 [['Karameller syrliga sockerfria']]
Risrätter 
 [['Paella']]
Dryck 
 [['Mandeldryck']]
Tacoskal 
 [['Tacoskal']]
Riskakor 
 [['Riskakor fullkorn solrosfrön majs fett 4%'
  'Riskakor fullkorn smaksatta fett 18%']]
Frukt o nötblandningar bars 
 [['Energibar choklad nötter Start'
  'Müslibar fullkorn berikad typ Special K Bar Red fruit']]
Frukt o bär 
 [['Havtorn' 'Aronia']]
Sportdrycker energidrycker 
 [['Sportdryck drickf' 'Energidryck typ Red Bull berikad']]
Gelatin agar agar 
 [['Agar torkad' 'Gelatinblad gelatinpulver']]
Övrigt 
 [['Samarinpulver' 'Samarin drickf']]
Blodmat 
 [['Gris blod rå' 'Nöt blod rå']]
Tuggummi 
 [['Tuggummi' 'Tuggummi sockerfritt']]
Kakaoprodukter 
 [['Kakaopulver fett 20-22%' "Kakaopulver m socker fett 2,5% typ O'boy"]]
Cider alkol

Den här klassificeringen är alltså den som Livsmedelsverket själva har gjort, och det går att ändra parametrarna här ovan och få fram mycket mer om den.

Men vad händer om man baserar en gruppering bara på näringsvärden i stället?

## Klustring av näringsvärden

Det finns över 50 näringsvärden i databasen.

Av de över 50 näringsvärdena får man välja ut ett antal som man tror kan spela roll för att ge livsmedlen en viss "profil". 

I princip skulle man kunna ha alla näringsvärden med, och man kan testa sig fram. Men på något sätt tror jag att de näringsvärden där många livsmedel har noll-värden kommer att förvirra klustringen.

De här tror jag ger en bra bild av rymden av livsmedel. 
```
[2 'Energi_kcal' 'REAL' 0 None 0]
[4 'Kolhydrater_g' 'REAL' 0 None 0]
[5 'Fett_g' 'REAL' 0 None 0]
[6 'Protein_g' 'REAL' 0 None 0]
[7 'Fibrer_g' 'REAL' 0 None 0]
[8 'Vatten_g' 'REAL' 0 None 0]
[9 'Alkohol_g' 'REAL' 0 None 0]
[10 'Aska_g' 'REAL' 0 None 0]
[42 'Vitamin_C_mg' 'REAL' 0 None 0]
[50 'Jarn_mg' 'REAL' 0 None 0]
```

In [120]:
#Här är det urval som används nu
#relevant_columns = [ 2,  4,  5,  6,  7,  8,  9, 10, 42, 50]
#relevant_columns = [2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54, 55, 56, 57]
relevant_columns = [ 4,  5,  6,  7,  8,  9]


#Här är alla möjliga dimensioner. En del försvinner eftersom de 
#har värden som saknas för vissa livsmedel
#[ 2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54, 55, 56, 57]

Variabeln columns används för att hålla de värden som ska klustras. Vid klustringen undersöker algoritmen om man kan hitta några grupper av livsmedel som är mer lika än andra. Den slumpar ut kluster-mittpunkter och ser vilka livsmedel som ligger närmast dem (i alla dimensioner). Därefter ändrar den mittpunkterna lite, räknar om och ser om det blev bättre.

Lite om numpy: i numpy kan man använda en array som index, men det gäller att göra det till ett index för kolumnerna och inte för raderna... (Läs mer om array som index här: <http://infontology.typepad.com/infontokod/2017/11/bra-funktioner-i-numpy.html> Där står också om den här "slice"-notationen array[a:b,c:d])

In [121]:
columns = dataset[:,relevant_columns] #Tar man bort ':,' blir det alltså ett urval rader
print(columns)

[[0.0 71.0 7.0 0.0 21.7 0.0]
 [0.0 85.0 2.8 0.0 11.1 0.0]
 [0.0 100.0 0.0 0.0 0.0 0.0]
 ...
 [7.6 0.5 0.93 0.8 90.0 0.0]
 [72.6 3.55 5.63 12.2 6.0 0.0]
 [57.5 4.8 8.44 1.75 27.5 0.0]]


Det går förstås att välja en massa olika klustringsalgoritmer. Vi har valt k-means. Det finns också en hel del parametrar att välja. <http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html>

In [122]:
 def cluster(dataset):
    kmeans = KMeans(n_clusters=numClusters, verbose=0, n_init=100)
    kmeans.fit(dataset)

    centroids = kmeans.cluster_centers_
    clusters = kmeans.labels_
    
    #Utskriften kommer ju inte här, utan efter funktionsanropet
    if debug:
        print (centroids)
        print (clusters)

    return clusters, centroids

In [123]:
#Livsmedelsdatabasen innehåller över 100 huvudgrupper. Det hade varit bra att ha något 
#färre grupper på översta nivån. Högst 50. Eller kanske bara 10, för att komma ner i något som
#skulle kunna motsvara "frukt, grönsaker, fisk, kött, nötter" etc.
numClusters = 20

In [124]:
clusters, centroids = cluster(columns)

[[ 5.88027322e+00  8.08109290e+00  6.65087432e+00  8.56939891e-01
   7.56477049e+01  1.06049180e+00]
 [ 5.83880597e+01  2.52385075e+01  7.43791045e+00  3.38253731e+00
   3.78597015e+00  1.94289029e-16]
 [ 4.59819048e+01  2.19983333e+01  6.09000000e+00  1.80476190e+00
   2.24650000e+01 -8.32667268e-17]
 [ 6.74952577e+01  4.52958763e+00  9.26979381e+00  7.69855670e+00
   8.51824742e+00  3.33066907e-16]
 [ 9.26315789e-02  9.77868421e+01  3.08947368e-01  1.00000000e-02
   1.62526316e+00 -8.32667268e-17]
 [ 2.38121212e+00  2.73833333e+01  1.96392424e+01  1.18030303e-01
   4.65059091e+01  1.94289029e-16]
 [ 3.21542289e-01  3.14666667e+00  2.05713433e+01  3.55223881e-02
   7.41916418e+01  4.99600361e-16]
 [ 2.50408333e+01  1.40789286e+01  7.44773810e+00  1.58392857e+00
   4.91957143e+01  5.89285714e-01]
 [ 4.47954416e+00  9.91253561e-01  1.62282051e+00  1.21763533e+00
   9.06939031e+01  1.96039886e-01]
 [ 2.17445122e+01  3.97463415e+00  4.86993902e+00  2.13780488e+00
   6.57578659e+01  3.1603

Clusters är en array som är lika lång som antalet rader i dataset:

In [125]:
print(clusters, "Antal värden:", len(clusters))

[10  4  4 ...  8  3 15] Antal värden: 2088


Beroende på hur man väljer parametrarna vid klustringen kan man få liten eller stor variation i hur många som hamnar i de olika klustren.

Här är en tabell med fördelningen, och med några enkla statistiska mått.

In [127]:
unique, counts = np.unique(clusters, return_counts=True) #https://stackoverflow.com/questions/28663856/how-to-count-the-occurrence-of-certain-item-in-an-ndarray-in-python
cluster_distribution = np.array(list(zip(unique, counts)))
print(cluster_distribution)
print("Medelvärde:", np.mean(cluster_distribution.T[1]))
print("Median:", np.median(cluster_distribution.T[1]))
print("Standardavvikelse:",np.std(cluster_distribution.T[1]))

[[  0 183]
 [  1  67]
 [  2  42]
 [  3  97]
 [  4  19]
 [  5  66]
 [  6 201]
 [  7  84]
 [  8 351]
 [  9 164]
 [ 10  38]
 [ 11  20]
 [ 12  19]
 [ 13 147]
 [ 14  41]
 [ 15  84]
 [ 16  59]
 [ 17 127]
 [ 18 249]
 [ 19  30]]
Medelvärde: 104.4
Median: 75.5
Standardavvikelse: 86.16751127890372


## Huvudgrupper i relation till kluster

Jag vet inte hur Livsmedelsverket har gjort när de har satt ihop sin lista av huvudgrupper. Jag tror att den bygger mycket på tradition.

När jag började titta på klustring begränsade jag beräkningarna till bara fett, protein och kolhydrater, och då hamnade mesosten i samma kluster som knäckebrödet, på grund av sin höga andel kolhydrater. Det var lite oväntat, men rymden av näringsvärden är ju helt ovetande om mänskliga måltidstraditioner eller inköpsmönster.

En av poängerna med att titta på kluster är att få en uppfattning just om vilka livsmedel som hänger ihop näringsmässigt. Om man vill skulle det sen vara möjligt att ta ett visst livsmedel, exempelvis _bläckfisk_, och fråga vilka andra livsmedel som näringsmässigt ligger nära bläckfisken. Det kanske visar sig att tofu eller drickyoghurt ligger lika nära som torsk eller blåmusslor.

Nu efter att klustringen är gjord går det att se vilka livsmedel som ingår i varje kluster, och vilka huvudgrupper de ingår i.

In [128]:
valt_kluster = 11

In [129]:
livsmedel_i_kluster = dataset[np.where(clusters==valt_kluster)][:,[0,60]]
print(livsmedel_i_kluster)

[['Cashewnötter' 'Nötter frön']
 ['Hasselnötter' 'Nötter frön']
 ['Jordnötssmör' 'Nötter frön']
 ['Jordnötter torkade' 'Nötter frön']
 ['Jordnötter rostade' '']
 ['Jordnötter rostade saltade' 'Nötter frön']
 ['Kokosflingor torkade' 'Nötter frön']
 ['Linfrön torkade' 'Nötter frön']
 ['Paranötter' 'Nötter frön']
 ['Pekannötter' 'Nötter frön']
 ['Pistaschnötter' 'Nötter frön']
 ['Pumpafrön squashfrön torkade' 'Nötter frön']
 ['Sesamfrön torkade' 'Nötter frön']
 ['Sesamfrön torkade u skal' 'Nötter frön']
 ['Solrosfrön torkade' 'Nötter frön']
 ['Sötmandel torkad' 'Nötter frön']
 ['Valnötter' 'Nötter frön']
 ['Pesto' 'Sås dressing majonnäs']
 ['Pestosås m basilika pinjenötter cashewnötter' 'Sås dressing majonnäs']
 ['Rostad lök' 'Grönsaks- rotfrukts- baljväxträtter och produkter']]


Eftersom det är så många livsmedel i varje kluster är det lättare att visa dem som en fördelning:

In [130]:
a=dataset[np.where(clusters==valt_kluster)][:,[0,60]]
unique, counts = np.unique(a.T[1], return_counts=True) #https://stackoverflow.com/questions/28663856/how-to-count-the-occurrence-of-certain-item-in-an-ndarray-in-python
huvudgrupp_distribution = np.array(list(zip(unique, counts)))

print(huvudgrupp_distribution)

[['' '1']
 ['Grönsaks- rotfrukts- baljväxträtter och produkter' '1']
 ['Nötter frön' '16']
 ['Sås dressing majonnäs' '2']]


Om man sorterar blir det lättare att få en uppfattning av vad klustret egentligen innehåller. 

In [131]:
order=np.argsort(huvudgrupp_distribution.T[1].astype(int))
order = np.flipud(order)
#print (order)
huvudgrupp_distribution = huvudgrupp_distribution[order]
print(huvudgrupp_distribution)

[['Nötter frön' '16']
 ['Sås dressing majonnäs' '2']
 ['Grönsaks- rotfrukts- baljväxträtter och produkter' '1']
 ['' '1']]


När jag körde fick jag en gång dessa som största kategorier i ett kluster:
    
```
['Korv' '17']
['Kött färskt fryst tillagat' '16']
['Pizza paj pirog färdig smörgås' '13']
['Köttprodukter kötträtter' '12']
['Fisk o skaldjursprodukter o rätter' '12']
['Starksprit' '6']
```

Jag antar att det hänger ihop med det höga energiinnehållet i spriten. Det är ju ingen som skulle föreslå att byta ut korven i middagen mot en sup, men kanske kan man tänka omvänt, att om man dricker mycket alkohol så motsvarar det rätt mycket korv.

Men även om man tycker att man har fått en stor andel av en viss huvudgrupp i sitt kluster, så kanske det ändå är bara en liten andel av hela huvudgruppen. 

Jag gjorde några beräkningar till, för att få fram hur stor del av huvudgruppen som man har prickat rätt:

In [132]:
totals = np.array([])
for item in huvudgrupp_distribution:
    a=np.where(huvudgrupp_storlek.T[0] == item [0])
    totals=np.append(totals,huvudgrupp_storlek[a[0],1])
samlad_array = np.concatenate((huvudgrupp_distribution.T,[totals]),axis=0).T
part = lambda x: np.divide(x[1].astype(int),x[2].astype(int))
andel = part(samlad_array.T)
samlad_array = np.vstack((samlad_array.T,andel.T))
print ("Namn,", "Antal i kluster,", "Totalt i huvudgrupp,", "Andel av huvudgrupp")
print (samlad_array.T)    

Namn, Antal i kluster, Totalt i huvudgrupp, Andel av huvudgrupp
[['Nötter frön' '16' '21' '0.7619047619047619']
 ['Sås dressing majonnäs' '2' '79' '0.02531645569620253']
 ['Grönsaks- rotfrukts- baljväxträtter och produkter' '1' '55'
  '0.01818181818181818']
 ['' '1' '7' '0.14285714285714285']]


Det här är kanske så långt vi kommer i det här resonemanget. En början till att jämföra Livsmedelsverkets klassificering med den klassificering man får om man _bara_ ser till näringsvärden i olika kombinationer.

En av de saker som drev mig till detta var de småkategorier som fanns bland Huvudgrupperna. Det skulle vara så bra om man kunde stoppa in dem i större kategorier. Men kanske går det inte. I alla fall inte baserat endast på näringsinnehåll.

Det här tillvägagångssättet går förstås att effektivisera extremt mycket. Den här essän är bara skriven av pedagogiska skäl (dels för att visa potentialen i Jupyter, och dels för att visa upp rymden av livsmedelsdata).

Man skulle till nästa essä kunna hålla fast vid möjligheten att det finns en korrespondens mellan huvudgrupper och näringsvärden, och kunna se vilka kombinationer av näringsvärden (och antal kluster) som ger best match mot huvudgrupperna. Det kräver massor av beräkningar! För varje antal kluster, välj alla kombinationer av näringsvärden: först enskilda näringsvärden, sen grupper av två, grupper av tre och så vidare. Och så måste man förstås hitta ett bra mått. Det måste man kanske också pröva sig fram till... Undrar om det finns ett matematiskt sätt att hitta det också, eller om det bara är möjligt att köra det så här med numeriska metoder...